[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
bla = "2Z9iGJD2L5WUycxNzjvE7E1RNR5ExHsrpRggopBQZFrb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
